# Generated by Django 5.2.17 on 2026-09-06 22:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAWAL', 'Retiro'), ('TRANSFER', 'Transferencia')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETE', 'Completada'), ('FAILED', 'Fallida')], default='PENDING', max_length=15)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('ref_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP origen de la petición HTTP', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Información del cliente (Navegador/App)')),
                ('device', models.ForeignKey(blank=True, help_text='Dispositivo desde el cual se autorizó la transacción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='authentication.device')),
                ('wallet_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='wallet.wallet')),
                ('wallet_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('CREDIT', 'Crédito (Entrada +)'), ('DEBIT', 'Débito (Salida -)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='wallet.wallet')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'idempotency_keys',
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_user_idempotency_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_must_be_positive'),
        ),
    ]
